name: something
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

# 依赖库 声明了您的软件包所需的其他软件包。
# 要自动升级软件包依赖项到最新版本，请运行 `flutter pub upgrade --major-versions`。
# 或者，可以通过将下面的版本号更改为最新版本的 pub.dev 上可用的版本来手动更新依赖项。
# 要查看哪些依赖项有更新版本可用，请运行 `flutter pub outdated`。
dependencies:
  flutter:
    sdk: flutter

  # 下面这行代码将Cupertino Icons字体添加到您的应用程序中。
  # 使用CupertinoIcons类来显示iOS风格的图标。
  cupertino_icons: ^1.0.6
  flutter_swiper_view: ^1.1.8
  dio: ^5.5.0+1
  provider: ^6.1.2
  oktoast: ^3.4.0
  pull_to_refresh: ^2.0.0
  shared_preferences: ^2.2.3
  get_it: ^7.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # flutter_lints 库 包含了一组推荐的编码实践的lint。
  # 该库提供的lint集在根目录的 analysis_options.yaml 文件中激活。
  # 你可以在该文件中禁用特定的lint规则，并激活其他的lint规则。
  flutter_lints: ^3.0.0

# The following section is specific to Flutter packages.
# 下面的部分是Flutter包特有的。
flutter:
  # 下面这行代码将Material Icons字体添加到您的应用程序中。
  # 使用MaterialIcons类来显示Material风格的图标。
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  # 添加自定义字体到您的应用程序中，请在"flutter"部分中添加fonts部分。
  # 每个列表项都应该有一个"family"键，其值是字体系列名称，
  # 以及一个"fonts"键，其值是一个列表，提供字体文件及其描述。例如：

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
