name: jiayi
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_app_name: ^0.1.0
  flutter_lints: ^3.0.0

flutter_app_name:
  name: "蒋佳一"

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/
  fonts:
    # Add fonts from the fonts directory to the application.
    - family: MaShanZheng
      fonts:
        - asset: fonts/MaShanZheng-Regular.ttf

    - family: LiuJianMaoCao
      fonts:
        - asset: fonts/LiuJianMaoCao-Regular.ttf
